from __future__ import annotations

import logging
import os
from datetime import datetime
from typing import Any, Callable, Dict, List

_log = logging.getLogger(__name__)


def handle_bootstrap_admin(
    store: Any,
    *,
    admin_username: Callable[[], str],
    generate_bootstrap_password: Callable[[], str],
    hash_password: Callable[[str], str],
    utc_now: Callable[[], datetime],
    iso: Callable[[datetime], str],
    normalize: Callable[[str], str],
) -> Dict[str, Any]:
    username = admin_username()
    password = str(os.getenv("ADMIN_PASSWORD", "") or "")
    now = utc_now()
    with store._connect() as conn:
        row = conn.execute(
            "SELECT admin_username FROM admin_auth WHERE username_norm = ?",
            (normalize(username),),
        ).fetchone()
        if row is not None:
            return {
                "ok": True,
                "created": False,
                "username": str(row["admin_username"] or ""),
                "generated_password": False,
                "bootstrap_file": "",
            }

        generated = False
        if not password:
            password = generate_bootstrap_password()
            generated = True
        conn.execute(
            (
                "INSERT INTO admin_auth(admin_username, username_norm, password_hash, "
                "password_algo, password_set_at, failed_count, locked_until, is_disabled, "
                "token_version, updated_at) VALUES (?, ?, ?, ?, ?, 0, NULL, 0, 1, ?)"
            ),
            (
                username,
                normalize(username),
                hash_password(password),
                "pbkdf2_sha256",
                iso(now),
                iso(now),
            ),
        )

    bootstrap_file = ""
    if generated:
        bootstrap_file = store._write_admin_bootstrap_file(username=username, password=password)

    return {
        "ok": True,
        "created": True,
        "username": username,
        "generated_password": generated,
        "bootstrap_file": bootstrap_file,
    }


def handle_bootstrap_teachers(store: Any, *, regenerate_token: bool) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for teacher in store._list_teacher_identities():
        tid = str(teacher.get("teacher_id") or "").strip()
        if not tid:
            continue
        row = store._ensure_teacher_auth(
            teacher_id=tid,
            teacher_name=str(teacher.get("teacher_name") or "").strip() or tid,
            email=str(teacher.get("email") or "").strip() or None,
            regenerate_token=regenerate_token,
        )
        if row:
            rows.append(row)
    return rows


def write_admin_bootstrap_file(
    store: Any,
    *,
    username: str,
    password: str,
    utc_now: Callable[[], datetime],
    iso: Callable[[datetime], str],
) -> str:
    auth_dir = store.data_dir / "auth"
    auth_dir.mkdir(parents=True, exist_ok=True)
    path = auth_dir / "admin_bootstrap.txt"
    content = (
        "# Generated by auth bootstrap. Rotate password after first login.\n"
        f"username={str(username or '').strip()}\n"
        f"password={str(password or '').strip()}\n"
        f"generated_at={iso(utc_now())}\n"
    )
    path.write_text(content, encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except Exception:  # policy: allowed-broad-except
        _log.warning("failed to chmod admin bootstrap file: %s", path, exc_info=True)
    return str(path)
