from __future__ import annotations

from .wiring.assignment_wiring import (
    assignment_catalog_deps,
    assignment_generate_deps,
    assignment_generate_tool_deps,
    assignment_handlers_deps,
    assignment_io_handlers_deps,
    assignment_llm_gate_deps,
    assignment_meta_postprocess_deps,
    assignment_progress_deps,
    assignment_questions_ocr_deps,
    assignment_requirements_deps,
    assignment_submission_attempt_deps,
    assignment_today_deps,
    assignment_upload_confirm_deps,
    assignment_upload_draft_save_deps,
    assignment_upload_handlers_deps,
    assignment_upload_parse_deps,
    assignment_upload_query_deps,
    assignment_upload_start_deps,
    assignment_uploaded_question_deps,
)
from .wiring.chat_wiring import (
    chat_event_stream_deps,
    chat_handlers_deps,
    chat_job_process_deps,
    chat_job_repo_deps,
    chat_runtime_deps,
    chat_start_deps,
    chat_status_deps,
    chat_support_deps,
    chat_worker_deps,
    compute_chat_reply_deps,
    session_history_deps,
)
from .wiring.misc_wiring import (
    agent_runtime_deps,
    chart_agent_run_deps,
    content_catalog_deps,
    core_example_tool_deps,
    lesson_core_tool_deps,
    tool_dispatch_deps,
    upload_llm_deps,
    upload_text_deps,
)
from .wiring.student_wiring import (
    assignment_process_archive_deps,
    student_directory_deps,
    student_import_deps,
    student_ops_deps,
    student_submit_deps,
)
from .wiring.teacher_wiring import (
    teacher_assignment_preflight_deps,
    teacher_model_config_deps,
    teacher_provider_registry_deps,
)
from .wiring.worker_wiring import (
    process_archive_worker_deps,
    profile_update_worker_deps,
    upload_worker_deps,
)

# Keep this module strictly explicit: only public provider APIs are exported.
__all__ = [
    "assignment_catalog_deps",
    "assignment_generate_deps",
    "assignment_generate_tool_deps",
    "assignment_handlers_deps",
    "assignment_io_handlers_deps",
    "assignment_llm_gate_deps",
    "assignment_meta_postprocess_deps",
    "assignment_progress_deps",
    "assignment_questions_ocr_deps",
    "assignment_requirements_deps",
    "assignment_submission_attempt_deps",
    "assignment_today_deps",
    "assignment_upload_confirm_deps",
    "assignment_upload_draft_save_deps",
    "assignment_upload_handlers_deps",
    "assignment_upload_parse_deps",
    "assignment_upload_query_deps",
    "assignment_upload_start_deps",
    "assignment_uploaded_question_deps",
    "chat_event_stream_deps",
    "chat_handlers_deps",
    "chat_job_process_deps",
    "chat_job_repo_deps",
    "chat_runtime_deps",
    "chat_start_deps",
    "chat_status_deps",
    "chat_support_deps",
    "chat_worker_deps",
    "compute_chat_reply_deps",
    "session_history_deps",
    "agent_runtime_deps",
    "chart_agent_run_deps",
    "content_catalog_deps",
    "core_example_tool_deps",
    "lesson_core_tool_deps",
    "tool_dispatch_deps",
    "upload_llm_deps",
    "upload_text_deps",
    "assignment_process_archive_deps",
    "student_directory_deps",
    "student_import_deps",
    "student_ops_deps",
    "student_submit_deps",
    "teacher_assignment_preflight_deps",
    "teacher_model_config_deps",
    "teacher_provider_registry_deps",
    "upload_worker_deps",
    "profile_update_worker_deps",
    "process_archive_worker_deps",
]
