import type { MatrixCase } from './helpers/e2eMatrixCases'
import { registerMatrixCases } from './helpers/e2eMatrixCases'

const routingProviderCases: MatrixCase[] = [
  {
    id: 'F001',
    priority: 'P0',
    title: 'Routing page loads when routing and provider endpoints succeed',
    given: '/teacher/llm-routing and /teacher/provider-registry return success',
    when: 'Open the routing page',
    then: 'Page renders with actionable controls',
  },
  {
    id: 'F002',
    priority: 'P1',
    title: 'Provider failure degrades gracefully when routing succeeds',
    given: 'Routing endpoint succeeds and provider endpoint fails',
    when: 'Open the routing page',
    then: 'Provider area shows fallback error without page crash',
  },
  {
    id: 'F003',
    priority: 'P1',
    title: 'Routing failure degrades gracefully when provider succeeds',
    given: 'Provider endpoint succeeds and routing endpoint fails',
    when: 'Open the routing page',
    then: 'Routing area shows fallback error and supports retry',
  },
  {
    id: 'F004',
    priority: 'P0',
    title: 'Simulate request returns matched rule and channel',
    given: '/teacher/llm-routing/simulate is available',
    when: 'Run simulation from routing UI',
    then: 'Simulation result includes selected rule and target channel',
  },
  {
    id: 'F005',
    priority: 'P0',
    title: 'Create proposal appends item to proposal list',
    given: 'Proposal creation endpoint is available',
    when: 'Submit new routing proposal',
    then: 'New proposal appears in proposal list',
  },
  {
    id: 'F006',
    priority: 'P0',
    title: 'Approve proposal increments active version',
    given: 'A proposal is pending review',
    when: 'Review with approve action',
    then: 'Routing version increments and proposal is marked applied',
  },
  {
    id: 'F007',
    priority: 'P1',
    title: 'Reject proposal stores status and reason',
    given: 'A proposal is pending review',
    when: 'Review with reject action and reason',
    then: 'Proposal status is rejected with visible reason',
  },
  {
    id: 'F008',
    priority: 'P0',
    title: 'Rollback activates selected historical version',
    given: 'Routing history includes multiple versions',
    when: 'Run rollback to previous version',
    then: 'Current routing config reflects selected historical version',
  },
  {
    id: 'F009',
    priority: 'P0',
    title: 'Valid https provider can be created',
    given: 'New provider form has valid https base_url and key',
    when: 'Submit provider create',
    then: 'Provider appears and key is masked in response UI',
  },
  {
    id: 'F010',
    priority: 'P0',
    title: 'Provider id conflict against shared catalog is blocked',
    given: 'Provider id matches shared provider id',
    when: 'Submit provider create',
    then: 'UI shows conflict error and provider is not created',
  },
  {
    id: 'F011',
    priority: 'P1',
    title: 'Provider key rotation does not expose plaintext key',
    given: 'Provider exists and patch endpoint is available',
    when: 'Submit provider update with new api_key',
    then: 'Update succeeds and plaintext key is never displayed',
  },
  {
    id: 'F012',
    priority: 'P1',
    title: 'Provider delete performs soft disable',
    given: 'Provider exists and delete endpoint is available',
    when: 'Delete provider',
    then: 'Provider is no longer selectable in merged catalog',
  },
  {
    id: 'F013',
    priority: 'P1',
    title: 'Probe models success returns selectable model list',
    given: 'Provider supports upstream /models',
    when: 'Run probe-models action',
    then: 'Model list is returned and can be selected',
  },
  {
    id: 'F014',
    priority: 'P1',
    title: 'Probe models timeout does not block manual model entry',
    given: 'Probe-models call times out or fails',
    when: 'Attempt to configure model manually',
    then: 'Manual model entry remains enabled',
  },
]

registerMatrixCases('Teacher Routing and Provider Management', routingProviderCases)
