import type { MatrixCase } from './helpers/e2eMatrixCases'
import { registerMatrixCases } from './helpers/e2eMatrixCases'

const persistenceRecoveryCases: MatrixCase[] = [
  {
    id: 'G001',
    priority: 'P0',
    title: 'Invalid pinned skill value falls back to auto route',
    given: 'teacherSkillPinned has invalid stored value',
    when: 'Open teacher app',
    then: 'UI falls back to auto-route and payload omits skill_id',
  },
  {
    id: 'G002',
    priority: 'P0',
    title: 'Missing active agent falls back to default',
    given: 'teacherActiveAgentId is missing in local storage',
    when: 'Open teacher app and send chat',
    then: 'Payload uses default agent id',
  },
  {
    id: 'G003',
    priority: 'P1',
    title: 'Unknown workbench tab falls back to default tab',
    given: 'teacherWorkbenchTab is invalid',
    when: 'Open teacher app',
    then: 'Workbench opens with default tab selection',
  },
  {
    id: 'G004',
    priority: 'P0',
    title: 'Pending chat job resumes after refresh',
    given: 'teacherPendingChatJob contains active job metadata',
    when: 'Reload page',
    then: 'Polling resumes and reaches terminal status',
  },
  {
    id: 'G005',
    priority: 'P1',
    title: 'Active upload marker restores workflow context',
    given: 'teacherActiveUpload contains workflow job metadata',
    when: 'Reload page',
    then: 'Workflow mode and polling are restored automatically',
  },
  {
    id: 'G006',
    priority: 'P1',
    title: 'Local and server view-state conflict remains usable',
    given: 'local view-state and server view-state disagree',
    when: 'App performs sync',
    then: 'UI keeps a consistent usable session state',
  },
  {
    id: 'G007',
    priority: 'P1',
    title: 'Corrupt local JSON does not break main flow',
    given: 'Stored JSON for teacher keys is malformed',
    when: 'Open teacher app',
    then: 'App falls back safely and chat remains usable',
  },
  {
    id: 'G008',
    priority: 'P1',
    title: 'Local storage write failure is tolerated',
    given: 'Storage writes throw quota or permission error',
    when: 'Perform chat and workflow actions',
    then: 'Primary flows continue without hard crash',
  },
  {
    id: 'G009',
    priority: 'P1',
    title: 'Custom API base persists across refresh',
    given: 'apiBaseTeacher is customized',
    when: 'Reload and send request',
    then: 'Requests target the configured API base URL',
  },
  {
    id: 'G010',
    priority: 'P0',
    title: 'Refresh during confirm does not duplicate action',
    given: 'Confirm request was triggered and page is refreshed',
    when: 'Wait for terminal status',
    then: 'Final state is consistent and confirm is not duplicated',
  },
]

const mobileA11yCases: MatrixCase[] = [
  {
    id: 'H001',
    priority: 'P0',
    title: 'Mobile overlay closes both side panels',
    given: 'Mobile viewport with session and workbench panels open',
    when: 'Tap overlay',
    then: 'Both panels close',
  },
  {
    id: 'H002',
    priority: 'P1',
    title: 'Session menu aria-expanded reflects open state',
    given: 'Session menu trigger is visible',
    when: 'Open and close session menu',
    then: 'aria-expanded toggles correctly',
  },
  {
    id: 'H003',
    priority: 'P1',
    title: 'Keyboard-only open and close works for session menu',
    given: 'Keyboard focus is on menu trigger',
    when: 'Press Enter then Escape',
    then: 'Menu opens and closes without pointer input',
  },
  {
    id: 'H004',
    priority: 'P1',
    title: 'Mention panel remains keyboard navigable on narrow screens',
    given: 'Mobile width and mention panel opened',
    when: 'Use arrow keys and Enter',
    then: 'Selected token is inserted correctly',
  },
  {
    id: 'H005',
    priority: 'P1',
    title: 'Send button disabled state reflects pending job',
    given: 'A pending chat job exists',
    when: 'Inspect send control',
    then: 'Send button is disabled and status is visible',
  },
  {
    id: 'H006',
    priority: 'P2',
    title: 'High zoom still keeps composer and send reachable',
    given: 'Browser zoom is set near 200 percent',
    when: 'Try typing and sending',
    then: 'Composer and send controls remain visible and clickable',
  },
  {
    id: 'H007',
    priority: 'P2',
    title: 'Landscape mobile keeps critical controls reachable',
    given: 'Mobile landscape viewport',
    when: 'Open teacher app and interact',
    then: 'Core controls remain accessible',
  },
  {
    id: 'H008',
    priority: 'P2',
    title: 'Touch scrolling does not depend on desktop wheel routing',
    given: 'Touch device style scrolling path',
    when: 'Scroll long content with touch gestures',
    then: 'No desktop wheel-only regression appears',
  },
]

registerMatrixCases('Teacher Persistence and Recovery', persistenceRecoveryCases)
registerMatrixCases('Teacher Mobile and Accessibility', mobileA11yCases)
