import type { MatrixCase } from './helpers/e2eMatrixCases'
import { registerMatrixCases } from './helpers/e2eMatrixCases'

const skillWorkbenchCases: MatrixCase[] = [
  {
    id: 'C001',
    priority: 'P1',
    title: 'Skill search filters by id title and description',
    given: 'Skill catalog is loaded',
    when: 'Enter search text in skill filter',
    then: 'Only matching skills remain visible',
  },
  {
    id: 'C002',
    priority: 'P1',
    title: 'Favorites-only mode keeps insertion target stable',
    given: 'At least one skill is favorited',
    when: 'Enable favorites-only and insert token',
    then: 'Inserted token belongs to selected favorite skill',
  },
  {
    id: 'C003',
    priority: 'P1',
    title: 'Favorite state persists after reload',
    given: 'Favorite state was changed',
    when: 'Reload page',
    then: 'Favorite selections are restored from storage',
  },
  {
    id: 'C004',
    priority: 'P0',
    title: 'Pin current skill sends explicit skill_id',
    given: 'Skill card supports pin current',
    when: 'Pin and send message',
    then: 'Payload includes selected skill_id',
  },
  {
    id: 'C005',
    priority: 'P0',
    title: 'Auto-route mode omits skill_id',
    given: 'Current mode is pinned skill',
    when: 'Switch to auto-route and send message',
    then: 'Payload does not include skill_id',
  },
  {
    id: 'C006',
    priority: 'P1',
    title: 'Insert token uses current caret position',
    given: 'Caret is in middle of composer text',
    when: 'Click insert skill token',
    then: 'Token is inserted at caret position',
  },
  {
    id: 'C007',
    priority: 'P1',
    title: 'Use template appends and remains editable',
    given: 'Skill has at least one template prompt',
    when: 'Click use template',
    then: 'Template is inserted and composer remains editable',
  },
  {
    id: 'C008',
    priority: 'P1',
    title: 'Skills API failure falls back to bundled catalog',
    given: '/skills request fails',
    when: 'Open teacher app',
    then: 'Bundled skill list renders and chat still works',
  },
  {
    id: 'C009',
    priority: 'P1',
    title: 'Manual refresh toggles loading state correctly',
    given: 'Workbench shows refresh control',
    when: 'Click refresh skills',
    then: 'Control enters loading and re-enables on completion',
  },
  {
    id: 'C010',
    priority: 'P2',
    title: 'Collapse and expand preserves active tab',
    given: 'Active tab is workflow or skills',
    when: 'Collapse and reopen workbench',
    then: 'Previously active tab remains selected',
  },
  {
    id: 'C011',
    priority: 'P1',
    title: 'Agent card insertion sets matching agent_id',
    given: 'Agent card can insert @ token',
    when: 'Insert and send prompt',
    then: 'Payload agent_id matches inserted agent token',
  },
  {
    id: 'C012',
    priority: 'P1',
    title: 'Card insert and manual tokens produce coherent payload',
    given: 'User mixes card insertion and manual typing',
    when: 'Send prompt',
    then: 'Effective agent and skill selection is deterministic',
  },
]

const assignmentWorkflowCases: MatrixCase[] = [
  {
    id: 'D001',
    priority: 'P0',
    title: 'Assignment id is required before upload start',
    given: 'Workflow mode is assignment',
    when: 'Submit without assignment id',
    then: 'Validation blocks request to /assignment/upload/start',
  },
  {
    id: 'D002',
    priority: 'P0',
    title: 'Assignment files are required before upload start',
    given: 'Assignment id is provided',
    when: 'Submit without files',
    then: 'Validation blocks request and shows error',
  },
  {
    id: 'D003',
    priority: 'P0',
    title: 'Class scope requires class_name',
    given: 'Assignment scope is class',
    when: 'Submit with files but no class name',
    then: 'Validation blocks request and shows class requirement',
  },
  {
    id: 'D004',
    priority: 'P0',
    title: 'Student scope requires student_ids',
    given: 'Assignment scope is student',
    when: 'Submit with files but no student ids',
    then: 'Validation blocks request and shows student requirement',
  },
  {
    id: 'D005',
    priority: 'P1',
    title: 'Upload success writes active assignment job marker',
    given: '/assignment/upload/start returns job_id',
    when: 'Submit valid assignment upload',
    then: 'teacherActiveUpload is set with assignment job id',
  },
  {
    id: 'D006',
    priority: 'P1',
    title: 'Queued processing done states map to workflow chips',
    given: 'Status endpoint returns queued then processing then done',
    when: 'Polling runs',
    then: 'Workflow chips transition through expected labels',
  },
  {
    id: 'D007',
    priority: 'P0',
    title: 'Failed assignment status clears active upload marker',
    given: 'Active assignment upload exists',
    when: 'Status returns failed',
    then: 'Error is shown and teacherActiveUpload is cleared',
  },
  {
    id: 'D008',
    priority: 'P0',
    title: 'Draft save clears dirty markers',
    given: 'Assignment draft has local edits',
    when: 'Click save draft',
    then: 'Dirty flags clear and save confirmation appears',
  },
  {
    id: 'D009',
    priority: 'P0',
    title: 'Missing requirements disable confirm with reason',
    given: 'Draft includes requirements_missing fields',
    when: 'View confirm action',
    then: 'Confirm button is disabled with explanatory title',
  },
  {
    id: 'D010',
    priority: 'P0',
    title: 'Confirm action is duplicate-safe',
    given: 'Assignment confirm is available',
    when: 'Click confirm multiple times quickly',
    then: 'Exactly one /assignment/upload/confirm request is sent',
  },
  {
    id: 'D011',
    priority: 'P0',
    title: 'Successful confirm enters created terminal state',
    given: '/assignment/upload/confirm returns success',
    when: 'Click confirm',
    then: 'UI shows created state and clears active upload marker',
  },
  {
    id: 'D012',
    priority: 'P1',
    title: 'job_not_ready response preserves draft context',
    given: '/assignment/upload/confirm returns job_not_ready',
    when: 'Click confirm',
    then: 'Draft data remains and retry guidance is shown',
  },
  {
    id: 'D013',
    priority: 'P1',
    title: 'Refresh restores assignment polling from local marker',
    given: 'teacherActiveUpload has assignment job id',
    when: 'Reload page',
    then: 'Workflow resumes polling and reloads draft state',
  },
  {
    id: 'D014',
    priority: 'P1',
    title: 'Request body preserves files and answer_files fields',
    given: 'Upload includes files and answer_files',
    when: 'Submit assignment upload',
    then: 'Multipart payload includes all expected file fields',
  },
]

const examWorkflowCases: MatrixCase[] = [
  {
    id: 'E001',
    priority: 'P0',
    title: 'Exam upload requires paper files',
    given: 'Workflow mode is exam',
    when: 'Submit without paper files',
    then: 'Validation blocks request to /exam/upload/start',
  },
  {
    id: 'E002',
    priority: 'P0',
    title: 'Exam upload requires score files',
    given: 'Paper files are selected',
    when: 'Submit without score files',
    then: 'Validation blocks request and shows score file requirement',
  },
  {
    id: 'E003',
    priority: 'P1',
    title: 'Exam upload success writes active job marker',
    given: '/exam/upload/start returns job_id',
    when: 'Submit valid exam upload',
    then: 'teacherActiveUpload is set with exam job id',
  },
  {
    id: 'E004',
    priority: 'P1',
    title: 'Progress values update in legal sequence',
    given: 'Status endpoint returns progress updates',
    when: 'Polling runs to completion',
    then: 'Progress is non-negative and never regresses unexpectedly',
  },
  {
    id: 'E005',
    priority: 'P0',
    title: 'Edited exam draft fields round-trip correctly',
    given: 'Exam draft is loaded',
    when: 'Edit and save date class and max score then reload draft',
    then: 'Saved values persist exactly',
  },
  {
    id: 'E006',
    priority: 'P0',
    title: 'Exam confirm success shows summary outputs',
    given: '/exam/upload/confirm returns success',
    when: 'Click confirm',
    then: 'UI displays exam id and question count summary',
  },
  {
    id: 'E007',
    priority: 'P0',
    title: 'Confirmed exam status clears active upload marker',
    given: 'Active exam upload exists',
    when: 'Status returns confirmed',
    then: 'teacherActiveUpload is removed',
  },
  {
    id: 'E008',
    priority: 'P0',
    title: 'Failed exam status leaves clear diagnostic message',
    given: 'Active exam upload exists',
    when: 'Status returns failed',
    then: 'Failure reason is visible and workflow is recoverable',
  },
  {
    id: 'E009',
    priority: 'P1',
    title: 'Server-generated exam id is displayed when omitted',
    given: 'Client submits without exam_id',
    when: 'Upload starts successfully',
    then: 'Generated exam id is shown in UI',
  },
  {
    id: 'E010',
    priority: 'P1',
    title: 'Mixed score sources still create exam job',
    given: 'Score upload includes xlsx and image files',
    when: 'Submit exam upload',
    then: 'Job is created and enters processing',
  },
  {
    id: 'E011',
    priority: 'P1',
    title: 'Confirm remains disabled before parse done',
    given: 'Exam parse status is queued or processing',
    when: 'Inspect confirm action',
    then: 'Confirm control stays disabled',
  },
  {
    id: 'E012',
    priority: 'P1',
    title: 'Exam not-ready confirm response preserves context',
    given: '/exam/upload/confirm returns job_not_ready',
    when: 'Click confirm',
    then: 'Draft and status context remain for retry',
  },
  {
    id: 'E013',
    priority: 'P1',
    title: 'Assignment and exam forms keep isolated state',
    given: 'Both workflow forms have unsaved values',
    when: 'Switch between assignment and exam modes',
    then: 'Each form restores its own values only',
  },
  {
    id: 'E014',
    priority: 'P2',
    title: 'Collapsed workflow summary reflects active job only',
    given: 'Upload panel supports collapsed summary',
    when: 'Switch active jobs and collapse panel',
    then: 'Summary always shows latest active job metadata',
  },
]

registerMatrixCases('Teacher Skill Workbench', skillWorkbenchCases)
registerMatrixCases('Teacher Assignment Workflow', assignmentWorkflowCases)
registerMatrixCases('Teacher Exam Workflow', examWorkflowCases)
