import type { MatrixCase } from './helpers/e2eMatrixCases'
import { registerMatrixCases } from './helpers/e2eMatrixCases'

const chatCases: MatrixCase[] = [
  {
    id: 'A001',
    priority: 'P0',
    title: 'IME Enter does not submit during composition',
    given: 'Composer is in IME composing state',
    when: 'Press Enter',
    then: 'No request is sent to /chat/start',
  },
  {
    id: 'A002',
    priority: 'P0',
    title: 'Start request failure shows recoverable error',
    given: '/chat/start returns 500',
    when: 'Click send',
    then: 'Error is shown and composer is re-enabled',
  },
  {
    id: 'A003',
    priority: 'P0',
    title: 'Processing status transitions to final reply',
    given: '/chat/status returns processing then done',
    when: 'Send one message',
    then: 'Placeholder message is replaced by final reply',
  },
  {
    id: 'A004',
    priority: 'P0',
    title: 'Failed status clears pending state',
    given: '/chat/status returns failed with detail',
    when: 'Send one message',
    then: 'Readable failure is shown and pending state is cleared',
  },
  {
    id: 'A005',
    priority: 'P0',
    title: 'Cancelled status allows next send',
    given: '/chat/status returns cancelled',
    when: 'Send one message',
    then: 'Message is marked cancelled and next send is allowed',
  },
  {
    id: 'A006',
    priority: 'P1',
    title: 'Queued response shows queue metrics',
    given: '/chat/start returns lane queue position and size',
    when: 'Send one message',
    then: 'Queue hint displays position and size',
  },
  {
    id: 'A007',
    priority: 'P1',
    title: 'Visibility restore triggers immediate poll',
    given: 'A pending chat job exists from a queued start response',
    when: 'Document visibility changes to visible',
    then: 'Polling runs immediately and state refreshes',
  },
  {
    id: 'A008',
    priority: 'P0',
    title: 'Duplicate send is blocked while pending',
    given: 'A pending chat job exists',
    when: 'Click send repeatedly',
    then: 'Only one /chat/start call is made',
  },
  {
    id: 'A009',
    priority: 'P1',
    title: 'Context window contract holds for long inputs',
    given: 'Long conversation history exists',
    when: 'Send a very long prompt',
    then: 'Payload context is trimmed to contract limits',
  },
  {
    id: 'A010',
    priority: 'P1',
    title: 'Last valid invocation token wins',
    given: 'Composer contains multiple @agent and $skill tokens',
    when: 'Send message',
    then: 'Payload uses the last valid agent and skill tokens',
  },
  {
    id: 'A011',
    priority: 'P1',
    title: 'Mention insertion in middle keeps spacing',
    given: 'Cursor is in the middle of existing text',
    when: 'Insert mention token from panel',
    then: 'Surrounding text and spaces remain correct',
  },
  {
    id: 'A012',
    priority: 'P2',
    title: 'Mixed locale text parsing remains stable',
    given: 'Prompt includes mixed CJK and ASCII punctuation',
    when: 'Send message',
    then: 'Content is not corrupted or truncated',
  },
  {
    id: 'A013',
    priority: 'P1',
    title: 'Invocation-only input is blocked',
    given: 'Composer only contains invocation tokens',
    when: 'Click send',
    then: 'Message is not sent and input remains visible',
  },
  {
    id: 'A014',
    priority: 'P1',
    title: 'Shift+Enter inserts newline, Enter submits',
    given: 'Composer has one line',
    when: 'Press Shift+Enter then Enter',
    then: 'Newline is inserted first and message sends on Enter',
  },
  {
    id: 'A015',
    priority: 'P0',
    title: 'Delayed start survives session switch',
    given: '/chat/start is delayed and source session has pending message',
    when: 'Switch to another session and back',
    then: 'Source session keeps user message and placeholder',
  },
  {
    id: 'A016',
    priority: 'P1',
    title: 'Unknown terminal status falls back gracefully',
    given: '/chat/status returns unknown terminal value',
    when: 'Send message',
    then: 'UI enters fallback error state and does not hang',
  },
]

const sessionCases: MatrixCase[] = [
  {
    id: 'B001',
    priority: 'P0',
    title: 'New session becomes active immediately',
    given: 'Session sidebar is open',
    when: 'Click new session',
    then: 'A session_* id appears and is active',
  },
  {
    id: 'B002',
    priority: 'P1',
    title: 'Rename updates list, search, and view-state',
    given: 'An existing session supports rename',
    when: 'Rename the session',
    then: 'Title and search index update and view-state syncs',
  },
  {
    id: 'B003',
    priority: 'P0',
    title: 'Archive moves session out of active list',
    given: 'A session can be archived',
    when: 'Confirm archive action',
    then: 'Session disappears from active and appears in archived view',
  },
  {
    id: 'B004',
    priority: 'P1',
    title: 'Archive cancel keeps state unchanged',
    given: 'Archive confirm dialog is shown',
    when: 'Dismiss dialog',
    then: 'Menu closes and session state does not change',
  },
  {
    id: 'B005',
    priority: 'P1',
    title: 'Session search matches id, title, and preview',
    given: 'Multiple sessions with different ids and previews',
    when: 'Enter search text',
    then: 'Matching sessions are filtered correctly',
  },
  {
    id: 'B006',
    priority: 'P1',
    title: 'Session menu closes on outside click and Escape',
    given: 'Session menu is open',
    when: 'Click outside or press Escape',
    then: 'Menu closes and aria-expanded resets',
  },
  {
    id: 'B007',
    priority: 'P0',
    title: 'Pending reply stays in source session',
    given: 'Main and secondary sessions exist',
    when: 'Send in main and switch to secondary',
    then: 'Reply is attached only to main session',
  },
  {
    id: 'B008',
    priority: 'P1',
    title: 'Session-local transient errors do not leak',
    given: 'Session A has a transient error state',
    when: 'Switch to session B',
    then: 'Session B has no leaked error banner',
  },
  {
    id: 'B009',
    priority: 'P1',
    title: 'Load-more sessions disabled at end cursor',
    given: 'Session list has no next cursor',
    when: 'Inspect load-more control',
    then: 'Button is disabled with terminal label',
  },
  {
    id: 'B010',
    priority: 'P1',
    title: 'Load older messages disabled at beginning',
    given: 'Current session has no older cursor',
    when: 'Inspect load-older control',
    then: 'Button is disabled with no-more label',
  },
  {
    id: 'B011',
    priority: 'P0',
    title: 'Draft session persists across page reload',
    given: 'Draft session exists locally but not server-persisted',
    when: 'Reload page',
    then: 'Draft session remains visible in sidebar',
  },
  {
    id: 'B012',
    priority: 'P2',
    title: 'Long sidebar list does not scroll bleed',
    given: 'Sidebar has long session list',
    when: 'Perform continuous scroll',
    then: 'Main page does not scroll through the sidebar',
  },
]

registerMatrixCases('Teacher Chat Invocation and Async', chatCases)
registerMatrixCases('Teacher Session Sidebar and History', sessionCases)
